services:

  web:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./web:/usr/share/nginx/html


  api:
    build: 
      context: ./api
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=tajinedb
      - DB_USER=yass
      - DB_PASSWORD=root
    depends_on:
      - db


  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - mydata:/var/lib/postgresql
      - ./db/init:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER=yass
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=tajinedb

volumes:
  mydata:


